stages:          
  - build
  - deploy

build-job:
  image: node:latest
  stage: build
  only:
    - master
    - dev
  except:
    - tags
  script:
    - echo "Build project..."
    - npm install

deploy-job:
  image: docker:latest
  stage: deploy 
  only:
     - master
  except:
     - tags

  script:
    - echo "Do docker image..."
    - docker build -t social_network_front .
    - cd /home/gitlab-runner/ && docker-compose up -d
