stages:          
  - build
  - deploy

build-job:
  image: node:latest
  stage: build
  only:
    - master
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "Build project..."
    - npm install

deploy-job:
  image: docker:latest
  stage: deploy 
  only:
     - master
  except:
     - tags

  script:
    - echo "do deploy"
    - cd /home/gitlab-runner/ 
    - docker-compose up --build -d
    - docker system prune -a -f --volumes
