stages:          
  - build
  - deploy

build-job:
  image: node:latest
  stage: build
  only:
    - master
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "Build project..."
    - npm install

deploy-job:
  stage: deploy 
  only:
     - master
  except:
     - tags
  script:
    - echo "do deploy"
    - cd /home/gitlab-runner/postgres/ 
    - docker-compose up -d
    - cd ./../
    - PGPASSWORD="iddqd"  pg_dump --host=localhost --username=javapro --file=backup/dbbackup.tar --format=tar
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker system prune -a -f --volumes

