stages:          
  - build
  - deploy

build-job:
  image: node:latest
  stage: build
  only:
    - master
    - dev
    - merge_request
  except:
    - tags
  script:
    - echo "Build project..."
    - npm install

deploy-job:
  image: docker:latest
  stage: deploy 
  only:
     - master
  except:
     - tags

  script:
    - echo "Do docker dark job he-he..."
    - docker system prune -a -f
    - cd /home/gitlab-runner/ && docker-compose down && docker-compose up -d
